repos:
  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v3.6.0
  #   hooks:
  #     - id: conventional-pre-commit
  #       stages:
  #         - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
        args: [ "--maxkb=800" ]
      - id: check-case-conflict
      - id: check-json
        # Exclude non-standard JSON
        exclude: |
            (?x)^(
                .devcontainer/devcontainer.json|
                .vscode/tasks.json
            )$
      - id: check-merge-conflict
      # Seems to flag false positives
      # - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: |
            (?x)^(
                helm/.*/templates/.*\.yaml$
            )$
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
        # Exclude non-standard JSON
        exclude: |
            (?x)^(
                .devcontainer/devcontainer.json|
                .vscode/tasks.json
            )$
      - id: trailing-whitespace
      #- id: no-commit-to-branch
      #  args: ['--pattern', '^(?!((task|bug|bugfix|fix|feat|feature|chore|spike|hotfix)\/[a-zA-Z0-9\-_]+)$).*$']
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
      - id: shellcheck
  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v1.1.1
    hooks:
      - id: markdown-toc
        files: README\.md$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words
          - .codespellignore
          - --write-changes
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: conventional-branch-name
        name: Check conventional branch name
        entry: bash -c 'branch=${BRANCH_NAME:-$(git rev-parse --abbrev-ref HEAD)}; if [[ ! $branch =~ ^main|(feature|feat|fix|bugfix|hotfix|major)/[a-z0-9\-]+$ ]]; then echo "❌ Invalid branch name:" "$branch"; exit 1; fi; echo "✅ Branch name is valid."'
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-write=true
      # TODO: Uncomment once this issue is resolved https://github.com/terraform-docs/terraform-docs/issues/836
      # - id: terraform_docs
      #   args:
      #     - --hook-config=--path-to-file=README.md
      #     - --hook-config=--add-to-existing-file=true
      #     - --hook-config=--create-file-if-not-exist=true
      - id: terraform_validate
        # TODO: Add future module directories here or a sensible regex to match them all
        files: ^terraform-azurerm-conditional-access/
        args:
          - --args=-json
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-upgrade
      - id: terraform_tflint
        args:
          - --args=--recursive
          - --args=--color
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact
          - --args=--skip-check "CKV_GHA_7"
      - id: terraform_trivy
        args:
          - --args=--skip-dirs="**/.terraform"
